### ISSUE TITLE
对一个测例的疑问

### ISSUE THREAD

**Issue by ErictheSam** [Yourens/decaf_PA2_2018#3]
我在readme中间得到了foreach语句的书写方法，发现其叙述中不需要支持while B缺省的语句
![1183270971](https://user-images.githubusercontent.com/40827319/50063498-8dd30200-01e7-11e9-8cb4-9fb6bce69e34.jpg)
而在测例中，我发现q53-4.decaf中间存在while B缺省语句，和readme自相矛盾
![1418283141](https://user-images.githubusercontent.com/40827319/50063536-c4108180-01e7-11e9-85cc-3240b77d1684.jpg)
这让我感到十分关切，希望尽快得到解答。

**Comment by Yourens** [comment]
语法的定义从PA1A开始，到之后的PA都不会有变化。

**Comment by ErictheSam** [comment]
呱？但是我没有在任何场合看见过这个“语法定义未变化”的声明啊

**Comment by Yourens** [comment]
README中红色字部分“因此语法和 PA1A 保持一致。”

**Comment by ErictheSam** [comment]
AAAAA...明白了

**Comment by ErictheSam** [comment]
好吧...我认输...做的时候注意过这句但是被后面的例子给带跑了...不过这一个错误不值得扣掉一分吧...

**Comment by ErictheSam** [comment]
总共测例有20多个，为什么错掉一个要扣分$\frac{1}{8}$呢...

**Comment by nonamenonameno** [comment]
助教的解释不合适吧？这不是认输不认输的问题，第一，pa2的readme中根本没有包含while语句缺失。第二，红色字部分不仅有“因此语法和 PA1A 保持一致”，还有“**同学们只需要完成下面列出的特性，其余语法本次试验不要求完成，以后的实验中也不会要求**”。
<img width="677" alt="2018-12-17 15 42 50" src="https://user-images.githubusercontent.com/44957272/50073316-3480c800-0213-11e9-8a46-52abcbd5ecd0.png">
readme中列出的特性不包含while语句缺失的情况，更与pa1a的语法不矛盾，更何况群里有同学问while的有关事宜，助教并没有给出确切的回复，这不是同学们的责任。

**Comment by Yourens** [comment]
不要求的意思是考虑到工作量太大去掉两个语法特性降低工作量。 列出的语法特性都需要按照PA1A的要求完成。具体语法特性的语法都在spec文件中有详细规范的定义。蓝色的readme的主要目的只是给同学提供hints。
